# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Test on orthus

on:
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  test:
    runs-on: self-hosted


    steps:
    - uses: actions/checkout@v3

    - name: Test orthus
      run: |
        echo "hello from orthus node `hostname`"
